networks:
  motorcyclemaintenance:
    driver: bridge

services:
  gateway-api:
    image: gateway-api
    container_name: gateway-api
    build:
      context: .
      dockerfile: ./src/Gateway/GateWay.Api/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - deliveryman-api
      - motorcycle-api
      - rent-api      
    restart: always
    networks:
      - motorcyclemaintenance

  deliveryman-api:
    image: deliveryman-api
    container_name: deliveryman-api
    build:
      context: .
      dockerfile: ./src/Services/DeliveryManService/DeliveryManService.Api/Dockerfile
    restart: always
    volumes:
      - cnh_image_data:/app/cnh_image
    networks:
      - motorcyclemaintenance
    depends_on:
      - mongodb

  motorcycle-api:
    image: motorcycle-api
    container_name: motorcycle-api
    build:
      context: .
      dockerfile: ./src/Services/MotorcycleService/MotorcycleService.Api/Dockerfile
    restart: always
    networks:
      - motorcyclemaintenance
    depends_on:
      - mongodb
      - rabbitmq

  rent-api:
    image: rent-api
    container_name: rent-api
    build:
      context: .
      dockerfile: ./src/Services/RentService/RentService.Api/Dockerfile
    restart: always
    networks:
      - motorcyclemaintenance
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - motorcyclemaintenance

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - motorcyclemaintenance

volumes:
  mongo_data:
  cnh_image_data:    